name: unify
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  uuid: ^3.0.4
  image_picker: ^0.8.3+2
  google_fonts:
  fading_edge_scrollview: ^2.0.1
  shrink_sidemenu:
  awesome_dialog:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
